CREATE TABLE T_TEAMS (
	ID VARCHAR(255) PRIMARY KEY NOT NULL,
	CREATED TIMESTAMP,
	LASTMODIFIED TIMESTAMP,
	TEAMNAME VARCHAR (255)
);

CREATE TABLE T_PERSONS (
	ID VARCHAR(255) PRIMARY KEY NOT NULL,
	CREATED TIMESTAMP,
	LASTMODIFIED TIMESTAMP,
	FIRSTNAME VARCHAR (255),
	LASTNAME VARCHAR (255),
	BIRTHDAY TIMESTAMP,
	T_TEAMS_ID VARCHAR(255) FOREIGN KEY REFERENCES T_TEAMS,
);
